### ISSUE TITLE
API 应该怎么填？

### ISSUE THREAD

**Issue by WanKa-zone** [caryyu/jellyfin-plugin-opendouban#11]
![image](https://user-images.githubusercontent.com/45703375/134933250-0cef5f59-03e1-4d16-a4a8-39dee8bb5e11.png)

这里是应该怎么填写？

不明白 “prefix URI“是改怎么填

**Comment by caryyu** [comment]
@Eadger 该插件需要依赖服务端项目 https://github.com/caryyu/douban-openapi-server

**Comment by WanKa-zone** [comment]
> @Eadger 该插件需要依赖服务端项目 https://github.com/caryyu/douban-openapi-server

[2021-09-28 13:39:26.871 +00:00] [ERR] [28] MediaBrowser.Providers.Manager.ProviderManager: Provider "TheMovieDb" failed to retrieve search results
TMDbLib.Objects.Exceptions.GeneralHttpException: TMDb returned an unexpected HTTP error
   at TMDbLib.Rest.RestRequest.SendInternal(HttpMethod method, CancellationToken cancellationToken)
   at TMDbLib.Rest.RestRequest.ExecuteGet[T](CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.SearchMethod[T](String method, String query, Int32 page, String language, Nullable`1 includeAdult, Int32 year, String dateFormat, String region, Int32 primaryReleaseYear, Int32 firstAirDateYear, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.SearchMovieAsync(String query, String language, Int32 page, Boolean includeAdult, Int32 year, String region, Int32 primaryReleaseYear, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.SearchMovieAsync(String name, Int32 year, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.TmdbMovieProvider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2021-09-28 13:39:27.040 +00:00] [INF] [30] Jellyfin.Plugin.Douban.MovieProvider: [DOUBAN] GetSearchResults ""
[2021-09-28 13:39:27.040 +00:00] [INF] [30] Jellyfin.Plugin.Douban.MovieProvider: [DOUBAN] Searching for sid of movie named ""
[2021-09-28 13:39:27.040 +00:00] [WRN] [30] Jellyfin.Plugin.Douban.MovieProvider: [DOUBAN] Search name is empty.
[2021-09-28 13:39:27.041 +00:00] [WRN] [30] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.1.2:8096/Items/RemoteSearch/Movie" to "172.17.0.1" in 0:00:00.6019436 with Status Code 200


运行
docker run --rm -d -p 5000:5000 caryyu/douban-openapi-server:latest
安装 后 

将ip地址填入Jellyfin
没有搜出结果

**Comment by caryyu** [comment]
@Eadger 可以尝试用影视资源中 Identify 输入关键字试试，从日志分析来看影视资源的标题没有被找到，所以空字符串是搜索不出来内容的。

**Comment by WanKa-zone** [comment]
> @Eadger 可以尝试用影视资源中 Identify 输入关键字试试，从日志分析来看影视资源的标题没有被找到，所以空字符串是搜索不出来内容的。

这是我直接填的豆瓣ID 出来的结果

**Comment by caryyu** [comment]
@Eadger 收到，我晚点测试一下

**Comment by caryyu** [comment]
@Eadger 我这边测试过了，利用 Identify 选项中填写 `OpenDouban Movie Id` 是可以正常工作的，日志中会展示如下：

```txt
[13:34:10] [INF] [22] Jellyfin.Plugin.OpenDouban.Providers.OddbMovieProvider: [Open DOUBAN] GetSearchResults of [sid]: "33440244"
```

**Comment by WanKa-zone** [comment]
> @Eadger 我这边测试过了，利用 Identify 选项中填写 `OpenDouban Movie Id` 是可以正常工作的，日志中会展示如下：
> 
> ```
> [13:34:10] [INF] [22] Jellyfin.Plugin.OpenDouban.Providers.OddbMovieProvider: [Open DOUBAN] GetSearchResults of [sid]: "33440244"
> ```

![image](https://user-images.githubusercontent.com/45703375/135691129-4e97b1c0-43b5-4412-b39e-d49f87b8e9c9.png)
是我这边docker没设置对吗？

**Comment by caryyu** [comment]
@Eadger 我看到你用了端口映射，取决于主容器地关联设置，你把 Jellyfin 的容器设置发我看看

**Comment by WanKa-zone** [comment]
> @Eadger 我看到你用了端口映射，取决于主容器地关联设置，你把 Jellyfin 的容器设置发我看看

我重新检查了所有的设置， 现在能使用了，应该是之前Jellyfin里面API没填对
