### ISSUE TITLE
最近又搜索不出来了

### ISSUE THREAD

**Issue by WanKa-zone** [caryyu/jellyfin-plugin-opendouban#22]
[2022-01-19 12:52:57.774 +00:00] [INF] [20] Jellyfin.Plugin.Douban.MovieProvider: [DOUBAN] GetSearchResults ""
[2022-01-19 12:52:57.779 +00:00] [INF] [20] Jellyfin.Plugin.Douban.MovieProvider: [DOUBAN] Searching for sid of movie named ""
[2022-01-19 12:52:57.779 +00:00] [WRN] [20] Jellyfin.Plugin.Douban.MovieProvider: [DOUBAN] Search name is empty.
[2022-01-19 12:52:57.784 +00:00] [INF] [20] Jellyfin.Plugin.OpenDouban.Providers.OddbMovieProvider: [Open DOUBAN] GetSearchResults of [sid]: "30396443"
[2022-01-19 12:53:04.289 +00:00] [ERR] [16] MediaBrowser.Providers.Manager.ProviderManager: Provider "OpenDouban" failed to retrieve search results
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (NOT FOUND).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.OpenDouban.OddbApiClient.GetBySid(String sid)
   at Jellyfin.Plugin.OpenDouban.Providers.OddbMovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2022-01-19 12:53:04.301 +00:00] [WRN] [16] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.1.238:8096/Items/RemoteSearch/Movie" to "172.17.0.1" in 0:00:07.9844472 with Status Code 200

**Comment by caryyu** [comment]
@Eadger 服务端返回了 404 ，你可以尝试使用服务端的接口手动调试看是不是 IP 被禁导致。
