### ISSUE TITLE
接口一直404

### ISSUE THREAD

**Issue by 907739769** [caryyu/jellyfin-plugin-opendouban#25]
[2022-01-30 11:33:15.416 +08:00] [INF] [4] Jellyfin.Plugin.OpenDouban.Providers.OddbMovieProvider: [Open DOUBAN] GetMetadata of [sid]: "1418834"
[2022-01-30 11:33:15.675 +08:00] [ERR] [24] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "OpenDouban"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (NOT FOUND).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.OpenDouban.OddbApiClient.GetBySid(String sid, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenDouban.Providers.OddbMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2022-01-30 11:33:15.677 +08:00] [INF] [24] Jellyfin.Plugin.OpenDouban.Providers.OddbImageProvider: [DOUBAN] GetImages for item: 断背山
[2022-01-30 11:33:15.866 +08:00] [ERR] [27] MediaBrowser.Providers.Manager.ProviderManager: "OddbImageProvider" failed in GetImageInfos for type "Movie" at "/movies/Brokeback Mountain (2005)/Brokeback Mountain (2005) Bluray-1080p.mp4"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (NOT FOUND).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.OpenDouban.OddbApiClient.GetBySid(String sid, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenDouban.Providers.OddbImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)

**Comment by 907739769** [comment]
![1](https://user-images.githubusercontent.com/27858369/151685738-662a284c-8678-4c29-8938-0c53d24b8055.png)
![2](https://user-images.githubusercontent.com/27858369/151685739-4b76f6cc-ab1b-4730-9a06-611939f0fcc7.png)

**Comment by 907739769** [comment]
openapi进行了端口映射 其他的默认设置

**Comment by 907739769** [comment]
[caryyu-douban-openapi-server.csv](https://github.com/caryyu/jellyfin-plugin-opendouban/files/7965262/caryyu-douban-openapi-server.csv)
openapi 日志

**Comment by 907739769** [comment]
docker 环境的时间晚了8小时，不知道有没有影响

**Comment by caryyu** [comment]
@907739769 我发现全部都是 404 资源没找到，你需要检查你容器内部的网络是否可以正常访问，如果不知道如何设置建议把容器网络改 Host 模式。

**Comment by 907739769** [comment]
> @907739769 我发现全部都是 404 资源没找到，你需要检查你容器内部的网络是否可以正常访问，如果不知道如何设置建议把容器网络改 Host 模式。

请问有修改默认5000端口的环境变量吗？5000端口已被NAS占用

**Comment by caryyu** [comment]
@907739769 可以查看 Dockerfile 文件是怎么做端口设置的，Dockerfile 命令行部分支持被覆盖的，可以去看看 Docker 的文档说明。
