### ISSUE TITLE
插件无法正常向后端服务器发送查询请求

### ISSUE THREAD

**Issue by yefoenix** [caryyu/jellyfin-plugin-opendouban#51]
插件版本：10.8.0.0
后端服务版本：caryyu/douban-openapi-server:c7e2a0f

先后在NAS本地和远程VPS服务器搭建了后端服务器，使用api访问验证可正常查询豆瓣内容，但在 Jellyfin 内自动扫描和手动输入ID查询均无法获得结果，Docker 日志显示没有收到插件的查询请求。

Jellyfin 相关日志如下：

> 
>  [2023-01-01 11:20:07.368 +08:00] [ERR] [25] MediaBrowser.Providers.Manager.ProviderManager: Provider "The Open Movie Database" failed to retrieve search results
> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
>  ---> System.TimeoutException: A task was canceled.
>  ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
>    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>    --- End of inner exception stack trace ---
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
>    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>    at MediaBrowser.Providers.Plugins.Omdb.OmdbItemProvider.GetSearchResultsInternal(ItemLookupInfo searchInfo, Boolean isSearch, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)

日志显示似乎查询的是 The Open Movie Database，但我实际输入的是 OpenDouban ID
![image](https://user-images.githubusercontent.com/8215230/210160237-e46c02c5-ddb6-46f5-821e-fd71e51d204c.png)

**Comment by yefoenix** [comment]
……发现是没有对相应媒体库启用 OpenDouban 插件，低级失误
